### PR TITLE
Update a homepage section

### PR DESCRIPTION
**Pull request by areeshatariq**
image

### CODE REVIEW

**Comment by skoudoro** [comment]
Thank you @areeshatariq!  Looks good to me. I need to try it locally and I will keep you updated.

**Comment by ShreyasFadnavis** [comment]
@areeshatariq looks great! A minor comment: Gibbs unringing is missing in the Preprocessing section!

**Comment by areeshatariq** [comment]
> @areeshatariq looks great! A minor comment: Gibbs unringing is missing in the Preprocessing section!

Added in  b84c2e4

**Comment by areeshatariq** [comment]
@skoudoro I have fixed the mobile view responsiveness issue

**Comment by skoudoro** [comment]
I will look into it now, thank you @areeshatariq

**Review by skoudoro — COMMENTED** [review]
ok, looks good! Thank you! merging

**Pull request merged**
