### PR TITLE
Updated the highlight section for laptop version

### PR DESCRIPTION
**Pull request by Mk996**

### CODE REVIEW

**Comment by Garyfallidis** [comment]
We usually put the images in dipy/dipy-data.

**Comment by Garyfallidis** [comment]
https://github.com/dipy/dipy_data

**Comment by Garyfallidis** [comment]
@skoudoro what you think about having the highlights in the ``dipy_web``.

**Comment by Garyfallidis** [comment]
?

**Comment by skoudoro** [comment]
This images will be hard to find and hard to reuse if they are not in Dipy-data.

Also, this make our environment less flexible in case of change.

**Comment by Mk996** [comment]
I am unsure how to move the highlight images into `dipy_data`. I have not worked on that. Can we have a call on this  Or some documentation that @Garyfallidis  @skoudoro  can share? 
Thanks!

**Comment by Garyfallidis** [comment]
You simply need to make a PR with the images here https://github.com/dipy/dipy_data

**Pull request merged**
